#!/usr/bin/env python3

# Dataset format (generated by `generate_synthetic_data.py`):
# - `train.npz` and `test.npz` contain keys:
#     - `x_d{d}_s0{s0}`: float32[N, L, d]  (state / prices X_t)
#     - `g_d{d}_s0{s0}`: float32[N, L]     (reward/payoff matrix R_t)
#   where L = num_exercise_opportunities = 9 for the paper's Table-1 setting.

import csv
import math
import os
import time

from tqdm import tqdm

import numpy as np
import torch
import torch.nn as nn


TABLE1_CONFIGS = [
    (20, 90),
    (20, 100),
    (20, 110),
    (50, 90),
    (50, 100),
    (50, 110),
    (100, 90),
    (100, 100),
    (100, 110),
    (200, 90),
    (200, 100),
    (200, 110),
]

NUM_EXERCISE_OPPORTUNITIES = 9

SEED = 20260220
LR = 1e-3
CLIPNORM = 5.0
MAX_EPOCHS = 100
TRAIN_UPDATES_PER_EPOCH = 200
EARLY_STOPPING_PATIENCE = 5
EARLY_STOPPING_MIN_DELTA = 0.0
VAL_FRACTION = 0.20

NUM_STACKED_LAYERS = 2
UNITS_HIDDEN = 20
OSPG_EPS = 1e-5
EVAL_MODE = "stochastic"  # "stochastic" or "stable"
BATCH_SIZE = 64
INFERENCE_BATCH_SIZE = 8192
OMIT_TIME_ZERO = True

BN_EPS = 1e-3
BN_MOMENTUM = 0.01  # PyTorch momentum = 1 - Keras momentum (Keras default 0.99)

#torch.backends.cuda.matmul.allow_tf32 = False

device = torch.device("cuda")
torch.set_default_dtype(torch.float32)

if not os.path.exists("train.npz"):
    raise FileNotFoundError("Missing train NPZ: train.npz")
if not os.path.exists("test.npz"):
    raise FileNotFoundError("Missing test NPZ: test.npz")
train_npz = np.load("train.npz")
test_npz = np.load("test.npz")

train_data = {k: np.array(train_npz[k], dtype=np.float32, copy=False) for k in train_npz.files}
test_data = {k: np.array(test_npz[k], dtype=np.float32, copy=False) for k in test_npz.files}
train_npz.close()
test_npz.close()
del train_npz
del test_npz

results = []
run_started = time.time()

with tqdm(
    TABLE1_CONFIGS,
    total=len(TABLE1_CONFIGS),
    desc="DNN-OSPG configs",
    unit="cfg",
    dynamic_ncols=True,
) as bar:
    for d_value, s0_value in bar:
        bar.set_postfix_str(f"d={int(d_value)} s0={int(s0_value)}", refresh=False)

        cfg_key = f"d{int(d_value)}_s0{int(s0_value)}"
        x_key = f"x_{cfg_key}"
        g_key = f"g_{cfg_key}"

        if x_key not in train_data or g_key not in train_data:
            raise KeyError(f"Missing keys in train.npz: {x_key} / {g_key}")
        if x_key not in test_data or g_key not in test_data:
            raise KeyError(f"Missing keys in test.npz: {x_key} / {g_key}")

        x_train = train_data[x_key]
        g_train = train_data[g_key]
        x_test = test_data[x_key]
        g_test = test_data[g_key]

        if x_train.ndim != 3 or g_train.ndim != 2:
            raise ValueError(
                f"Bad shapes for {cfg_key}: x={tuple(x_train.shape)} g={tuple(g_train.shape)}"
            )
        if x_train.shape[0] != g_train.shape[0] or x_train.shape[1] != g_train.shape[1]:
            raise ValueError(
                f"Train mismatch for {cfg_key}: x={tuple(x_train.shape)} g={tuple(g_train.shape)}"
            )
        if x_test.shape[0] != g_test.shape[0] or x_test.shape[1] != g_test.shape[1]:
            raise ValueError(
                f"Test mismatch for {cfg_key}: x={tuple(x_test.shape)} g={tuple(g_test.shape)}"
            )

        n_train, seq_len, d_in = x_train.shape
        if int(seq_len) != int(NUM_EXERCISE_OPPORTUNITIES):
            raise ValueError(f"Expected L={NUM_EXERCISE_OPPORTUNITIES}, got L={seq_len} for {cfg_key}")
        if int(d_in) != int(d_value):
            raise ValueError(f"d mismatch: expected {d_value}, got {d_in} for {cfg_key}")

        # Features are [t/L, reward, x_t] (reward input is always included).
        input_dim = int(d_in) + 2
        row_seed = int(SEED + int(d_value) * 1_000 + int(s0_value))
        rng = np.random.default_rng(row_seed)
        torch_gen = torch.Generator(device=device)
        torch_gen.manual_seed(row_seed)
        torch.manual_seed(row_seed)

        perm = rng.permutation(n_train)
        n_val = int(max(1, math.floor(VAL_FRACTION * n_train)))
        val_idx = perm[:n_val]
        train_idx = perm[n_val:]
        if train_idx.size < 1:
            raise ValueError(f"Train split empty for {cfg_key} (n_train={n_train}, n_val={n_val}).")

        time_template = (
            torch.arange(seq_len, device=device, dtype=torch.float32).view(1, seq_len, 1) / float(seq_len)
        )

        with torch.no_grad():
            train_features_all = torch.empty(
                (int(n_train), int(seq_len), int(input_dim)), device=device, dtype=torch.float32
            )
            train_features_all[:, :, 0:1].copy_(time_template.expand(int(n_train), -1, -1))
            train_features_all[:, :, 1].copy_(torch.from_numpy(g_train))
            train_features_all[:, :, 2:].copy_(torch.from_numpy(x_train))

            n_test_total = int(x_test.shape[0])
            test_features_all = torch.empty(
                (int(n_test_total), int(seq_len), int(input_dim)), device=device, dtype=torch.float32
            )
            test_features_all[:, :, 0:1].copy_(time_template.expand(int(n_test_total), -1, -1))
            test_features_all[:, :, 1].copy_(torch.from_numpy(g_test))
            test_features_all[:, :, 2:].copy_(torch.from_numpy(x_test))

            val_idx_t = torch.from_numpy(np.asarray(val_idx, dtype=np.int64)).to(device=device)
            val_features_all = train_features_all.index_select(0, val_idx_t)

        model = nn.Module()
        model.input_bn = nn.BatchNorm1d(input_dim, eps=float(BN_EPS), momentum=float(BN_MOMENTUM))
        model.hidden_layers = nn.ModuleList()
        model.hidden_bns = nn.ModuleList()
        in_dim = int(input_dim)
        for _ in range(int(NUM_STACKED_LAYERS)):
            model.hidden_layers.append(nn.Linear(in_dim, int(UNITS_HIDDEN)))
            model.hidden_bns.append(
                nn.BatchNorm1d(int(UNITS_HIDDEN), eps=float(BN_EPS), momentum=float(BN_MOMENTUM))
            )
            in_dim = int(UNITS_HIDDEN)
        model.output_layer = nn.Linear(in_dim, 1)
        model.relu = nn.ReLU()
        model.sigmoid = nn.Sigmoid()
        model.to(device)

        with torch.no_grad():
            for layer in model.hidden_layers:
                nn.init.xavier_uniform_(layer.weight)
                nn.init.zeros_(layer.bias)
            nn.init.xavier_uniform_(model.output_layer.weight)
            nn.init.zeros_(model.output_layer.bias)

        optimizer = torch.optim.Adam(model.parameters(), lr=float(LR))

        best_val_metric = -float("inf")
        best_state = None
        best_epoch = 0
        patience_counter = 0

        t_train_started = time.time()

        with tqdm(
            total=int(MAX_EPOCHS),
            desc=f"d={int(d_value)} p0={int(s0_value)}",
            position=1,
            leave=False,
            dynamic_ncols=True,
            unit="epoch",
        ) as inner_bar:
            inner_bar.set_postfix_str("train", refresh=False)

            for epoch in range(int(MAX_EPOCHS)):
                model.train()

                for _step in range(int(TRAIN_UPDATES_PER_EPOCH)):
                    batch_sel = rng.choice(train_idx, size=int(BATCH_SIZE), replace=True)
                    batch_sel_t = torch.from_numpy(np.asarray(batch_sel, dtype=np.int64)).to(device=device)
                    features = train_features_all.index_select(0, batch_sel_t)
                    reward = features[:, :, 1]

                    optimizer.zero_grad(set_to_none=True)

                    values = features
                    values = model.input_bn(values.transpose(1, 2)).transpose(1, 2)
                    for layer, bn in zip(model.hidden_layers, model.hidden_bns):
                        values = layer(values)
                        values = model.relu(values)
                        values = bn(values.transpose(1, 2)).transpose(1, 2)
                    values = model.output_layer(values)
                    phi = model.sigmoid(values).squeeze(-1)
                    if OMIT_TIME_ZERO:
                        phi = phi.clone()
                        phi[:, 0] = 0.0

                    phi32 = phi
                    reward_sum = torch.sum(reward, dim=1, keepdim=True)
                    reward_distribution = reward / (reward_sum + OSPG_EPS)

                    log_one_minus_phi = torch.log(torch.clamp(1.0 - phi32, OSPG_EPS, 1.0))
                    log_phi = torch.log(torch.clamp(phi32, OSPG_EPS, 1.0))

                    psi_j = torch.exp(torch.cumsum(log_one_minus_phi[:, :-2], dim=1) + log_phi[:, 1:-1])
                    psi_1 = phi32[:, 0:1]
                    psi_l = torch.exp(torch.sum(log_one_minus_phi[:, :-1], dim=1, keepdim=True))
                    psi = torch.cat([psi_1, psi_j, psi_l], dim=1)

                    r_ij = reward_distribution * reward_sum
                    r_a = r_ij - torch.mean(r_ij)
                    r_psi = (r_a * psi).detach()
                    pg_loss = torch.sum(r_psi * torch.log(torch.clamp(psi, OSPG_EPS, 1.0)), dim=1)
                    loss = -torch.mean(pg_loss)

                    loss.backward()
                    if float(CLIPNORM) > 0:
                        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=float(CLIPNORM))
                    optimizer.step()

                model.eval()
                with torch.no_grad():
                    val_total = 0.0
                    val_count = 0
                    val_chunk = int(max(1, min(int(INFERENCE_BATCH_SIZE), int(val_features_all.shape[0]))))
                    for start in range(0, int(val_features_all.shape[0]), int(val_chunk)):
                        end = min(start + int(val_chunk), int(val_features_all.shape[0]))
                        features = val_features_all[start:end]
                        reward = features[:, :, 1]

                        values = features
                        values = model.input_bn(values.transpose(1, 2)).transpose(1, 2)
                        for layer, bn in zip(model.hidden_layers, model.hidden_bns):
                            values = layer(values)
                            values = model.relu(values)
                            values = bn(values.transpose(1, 2)).transpose(1, 2)
                        values = model.output_layer(values)
                        phi = model.sigmoid(values).squeeze(-1)
                        if OMIT_TIME_ZERO:
                            phi = phi.clone()
                            phi[:, 0] = 0.0

                        phi32 = phi
                        log_one_minus_phi = torch.log(torch.clamp(1.0 - phi32, OSPG_EPS, 1.0))
                        log_phi = torch.log(torch.clamp(phi32, OSPG_EPS, 1.0))
                        psi_j = torch.exp(torch.cumsum(log_one_minus_phi[:, :-2], dim=1) + log_phi[:, 1:-1])
                        loss_j = torch.sum(reward[:, 1:-1] * psi_j, dim=1)
                        loss_1 = reward[:, 0] * phi32[:, 0]
                        loss_l = torch.exp(torch.sum(log_one_minus_phi[:, :-1], dim=1)) * reward[:, -1]
                        stable_reward = loss_1 + loss_j + loss_l

                        val_total += float(torch.sum(stable_reward).item())
                        val_count += int(stable_reward.numel())

                    val_metric = val_total / max(1, val_count)

                improved = val_metric > (best_val_metric + float(EARLY_STOPPING_MIN_DELTA))
                if improved:
                    best_val_metric = val_metric
                    best_epoch = epoch + 1
                    patience_counter = 0
                    best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
                else:
                    patience_counter += 1

                inner_bar.set_postfix_str(f"train val={val_metric:.3f} best={best_val_metric:.3f}", refresh=False)
                inner_bar.update(1)

                if int(patience_counter) > int(EARLY_STOPPING_PATIENCE):
                    break

            inner_bar.set_postfix_str("eval", refresh=False)

        t_train_sec = time.time() - t_train_started

        if best_state is not None:
            model.load_state_dict(best_state)
        model.eval()

        t_eval_started = time.time()
        n_total = int(test_features_all.shape[0])
        n_eval = n_total

        stable_total = 0.0
        stable_count = 0
        point_total = 0.0
        point_total_sq = 0.0
        point_count = 0

        with torch.no_grad():
            eval_chunk = int(max(1, min(int(INFERENCE_BATCH_SIZE), int(n_eval))))
            for start in range(0, int(n_eval), int(eval_chunk)):
                end = min(start + int(eval_chunk), int(n_eval))
                features = test_features_all[start:end]
                reward = features[:, :, 1]

                values = features
                values = model.input_bn(values.transpose(1, 2)).transpose(1, 2)
                for layer, bn in zip(model.hidden_layers, model.hidden_bns):
                    values = layer(values)
                    values = model.relu(values)
                    values = bn(values.transpose(1, 2)).transpose(1, 2)
                values = model.output_layer(values)
                phi = model.sigmoid(values).squeeze(-1)
                if OMIT_TIME_ZERO:
                    phi = phi.clone()
                    phi[:, 0] = 0.0

                phi32 = phi
                log_one_minus_phi = torch.log(torch.clamp(1.0 - phi32, OSPG_EPS, 1.0))
                log_phi = torch.log(torch.clamp(phi32, OSPG_EPS, 1.0))
                psi_j = torch.exp(torch.cumsum(log_one_minus_phi[:, :-2], dim=1) + log_phi[:, 1:-1])
                loss_j = torch.sum(reward[:, 1:-1] * psi_j, dim=1)
                loss_1 = reward[:, 0] * phi32[:, 0]
                loss_l = torch.exp(torch.sum(log_one_minus_phi[:, :-1], dim=1)) * reward[:, -1]
                stable_reward = loss_1 + loss_j + loss_l

                stable_total += float(torch.sum(stable_reward).item())
                stable_count += int(stable_reward.numel())

                if EVAL_MODE == "stochastic":
                    interventions = (phi32 >= torch.rand(phi32.shape, device=device, generator=torch_gen)).to(
                        dtype=torch.bool
                    )
                    interventions[:, -1] = True
                    if OMIT_TIME_ZERO:
                        interventions[:, 0] = False
                    stop_idxs = torch.argmax(interventions.to(dtype=torch.int64), dim=1)
                    path_idxs = torch.arange(stop_idxs.shape[0], device=device)
                    payoff = reward[path_idxs, stop_idxs]

                    point_total += float(torch.sum(payoff).item())
                    point_total_sq += float(torch.sum(payoff * payoff).item())
                    point_count += int(payoff.numel())

        stable_est = stable_total / max(1, stable_count)
        if EVAL_MODE == "stable":
            point_est = float(stable_est)
            point_std = 0.0
        else:
            point_est = point_total / max(1, point_count)
            point_var = 0.0
            if point_count > 1:
                point_var = max(0.0, (point_total_sq - point_count * point_est * point_est) / (point_count - 1))
            point_std = float(math.sqrt(point_var))

        t_eval_sec = time.time() - t_eval_started

        row = {
            "d": int(d_value),
            "s0": int(s0_value),
            "seed": int(row_seed),
            "n_train": int(n_train),
            "n_val": int(n_val),
            "n_test": int(n_total),
            "L": int(seq_len),
            "include_reward_input": True,
            "batchnorm": True,
            "num_stacked_layers": int(NUM_STACKED_LAYERS),
            "units_hidden": int(UNITS_HIDDEN),
            "lr": float(LR),
            "clipnorm": float(CLIPNORM),
            "max_epochs": int(MAX_EPOCHS),
            "train_updates_per_epoch": int(TRAIN_UPDATES_PER_EPOCH),
            "early_stopping_patience": int(EARLY_STOPPING_PATIENCE),
            "best_epoch": int(best_epoch),
            "best_val_stable": float(best_val_metric),
            "batch_size": int(BATCH_SIZE),
            "eval_mode": str(EVAL_MODE),
            "point_mc_paths": 0,
            "stable_reward_est": float(stable_est),
            "point_est": float(point_est),
            "point_std": float(point_std),
            "t_train_sec": float(t_train_sec),
            "t_eval_sec": float(t_eval_sec),
        }
        results.append(row)
        tqdm.write(f"Done d={int(d_value)} s0={int(s0_value)} | DNN-OSPG={row['point_est']:.3f}")

results = sorted(results, key=lambda r: (int(r["d"]), int(r["s0"])))

with open("baselines_dnn_ospg_results.csv", "w", newline="", encoding="utf-8") as handle:
    fieldnames = ["d", "p0", "DNN_OSPG_point", "DNN_OSPG_stable"]
    writer = csv.DictWriter(handle, fieldnames=fieldnames)
    writer.writeheader()
    for row in results:
        writer.writerow(
            {
                "d": int(row["d"]),
                "p0": int(row["s0"]),
                "DNN_OSPG_point": f'{float(row["point_est"]):.2f}',
                "DNN_OSPG_stable": f'{float(row["stable_reward_est"]):.2f}',
            }
        )
